// figma-props.mjs - Figma component properties as the code sees them: which are interaction states (not
// props), what each is called in code, and TypeScript types for them (idea I46).
//
// The types let a React or Vue project check its component props against Figma with the compiler, so prop
// drift shows in the editor and in `tsc`, not only in the audit:
//   import type { ChipFigmaProps } from '../contracts/figma-props';
//   export function Chip(props: ChipFigmaProps) { … }
// Written to contracts/figma-props.d.ts (contracts.propTypesOut to put it where CI can read it).

// A Figma "State" variant (hover/focus/active…) maps to CSS pseudo-classes, not to a code prop.
const STATE_WORDS = new Set(['default', 'hover', 'focus', 'focused', 'active', 'pressed',
  'selected', 'checked', 'indeterminate', 'visited', 'disabled', 'loading', 'error', 'on', 'off']);
const norm = (s) => String(s).toLowerCase().replace(/[^a-z0-9]/g, '');

// Figma property keys carry a node-id suffix: "Show Label#958:0" -> "Show Label".
export const cleanFigmaProp = (k) => String(k).replace(/#[\d:]+$/, '').trim();

// Skips a property named state/states (or ds-config knownStateProps, or a declared states axis with a
// value, I40), or a VARIANT whose options are all interaction states.
export function stateAxisTest(cfg = {}) {
  const declared = Object.values(cfg.states ?? {}).filter((s) => s?.prop && s.value != null).map((s) => s.prop);
  const names = new Set([...(cfg.knownStateProps ?? ['State', 'state', 'States']), ...declared].map(norm));
  return (name, def) => names.has(norm(name)) ||
    (def?.type === 'VARIANT' && Array.isArray(def.variantOptions) && def.variantOptions.length >= 2 &&
      def.variantOptions.every((o) => STATE_WORDS.has(norm(o))));
}

const camel = (s) => String(s).trim().replace(/[^A-Za-z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : '')).replace(/^[A-Z]/, (c) => c.toLowerCase());
const pascal = (s) => camel(s).replace(/^[a-z]/, (c) => c.toUpperCase());
const isBoolOptions = (opts) => Array.isArray(opts) && opts.length === 2 && opts.every((o) => /^(true|false)$/i.test(o));
const lit = (v) => JSON.stringify(String(v));

// The code name of a Figma property: an authored binding, then componentPropAliases, then camelCase.
export function codePropName(component, figmaProp, { authored = {}, aliases = {} } = {}) {
  const clean = cleanFigmaProp(figmaProp);
  const b = authored?.[component]?.bindings?.[clean] ?? authored?.[component]?.bindings?.[figmaProp];
  if (typeof b?.attribute === 'string') return b.attribute;
  if (b?.slot === true) return 'children';
  if (typeof b?.slot === 'string') return b.slot;
  return aliases?.[component]?.[clean] ?? aliases?.[component]?.[camel(clean)] ?? camel(clean);
}

// The declaration file for every component with properties in the props snapshot.
export function propTypesDts(propsSnapshot, { cfg = {}, authored = {} } = {}) {
  const isState = stateAxisTest(cfg);
  const aliases = cfg.componentPropAliases ?? {};
  const out = ['// Generated by rms-figma-code-parity from the Figma component properties. Do not edit: run the audit again.', ''];
  for (const [component, entry] of Object.entries(propsSnapshot ?? {}).sort(([a], [b]) => a.localeCompare(b))) {
    if (component.startsWith('_') || !entry?.properties) continue;
    const fields = [], defaults = [];
    for (const [key, def] of Object.entries(entry.properties)) {
      const figma = cleanFigmaProp(key);
      if (isState(figma, def)) continue;
      const name = codePropName(component, key, { authored, aliases });
      let type = 'unknown', dflt;
      if (def?.type === 'VARIANT' && isBoolOptions(def.variantOptions)) { type = 'boolean'; dflt = /^true$/i.test(def.defaultValue) ? 'true' : 'false'; }
      else if (def?.type === 'VARIANT' && Array.isArray(def.variantOptions) && def.variantOptions.length) { type = def.variantOptions.map(lit).join(' | '); if (def.defaultValue != null) dflt = lit(def.defaultValue); }
      else if (def?.type === 'BOOLEAN') { type = 'boolean'; if (def.defaultValue != null) dflt = String(!!def.defaultValue); }
      else if (def?.type === 'TEXT') { type = 'string'; if (def.defaultValue != null) dflt = lit(def.defaultValue); }
      const what = def?.type === 'INSTANCE_SWAP' ? 'an instance (a slot)' : String(def?.type ?? 'unknown').toLowerCase();
      fields.push(`  /** Figma: ${figma} (${what}) */\n  ${/^[A-Za-z_$][\w$]*$/.test(name) ? name : lit(name)}?: ${type};`);
      if (dflt != null) defaults.push(`  ${/^[A-Za-z_$][\w$]*$/.test(name) ? name : lit(name)}: ${dflt};`);
    }
    if (!fields.length) continue;
    const I = `${pascal(component)}FigmaProps`;
    out.push(`/** ${component}${entry.nodeId ? ` (Figma node ${entry.nodeId})` : ''} */`, `export interface ${I} {`, ...fields, '}');
    if (defaults.length) out.push(`/** The defaults Figma gives each property. */`, `export interface ${pascal(component)}FigmaDefaults {`, ...defaults, '}');
    out.push('');
  }
  return out.join('\n');
}
